routes/web.php
<?php
/*
  ./routes/web.php
  Routeur principal
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
*/

//  ROUTES AJAX      ===========================================================
/*
  CHARGEMENT DES OLDER POSTS
  PATTERN: /ajax/older-posts
  CTRL: Projets
  ACTION: ajaxOlders
 */
Route::get('/ajax/older-projects', 'ProjetsController@ajaxOlders')->name('projets.ajax.olders');

//  ROUTES STANDARDS ===========================================================

/*-----------------------------------
    PROJETS
-----------------------------------*/

Route::prefix('projets')->name('projets.')->group(function(){
/*
  DETAILS D'UN PROJET
  PATTERN: /projets/{projet}/{slug}.html [GET]
  CTRL: Projets
  ACTION: show
*/
Route::get('{projet}/{slug}.html', 'ProjetsController@show')
      ->where([
               'projet'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('show');
});

/*-----------------------------------
    POSTS
-----------------------------------*/

Route::prefix('posts')->name('posts.')->group(function(){
/*
  DETAILS D'UN POST
  PATTERN: /posts/{post}/{slug}.html [GET]
  CTRL: Posts
  ACTION: show
*/

Route::get('{post}/{slug}.html', 'PostsController@show')
      ->where([
               'post'   => '[1-9][0-9]*',
               'slug'   => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('show');
/*
  FLUX RSS - DERNIERS POSTS BASICA
  PATTERN: /posts/rss [GET]
  CTRL: PostsController
  ACTION: rss
*/
Route::get('rss', 'PostsController@index')->name('rss');

});

/*-----------------------------------
    TAGS
-----------------------------------*/
/*
  DETAILS D'UN TAG
  PATTERN: /tags/{tag}/{slug}.html [GET]
  CTRL: Tags
  ACTION: show
 */
Route::get('/tags/{tag}/{slug}.html', 'TagsController@show')
      ->where([
               'tag'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('tags.show');

/*-----------------------------------
    CATEGORIES
-----------------------------------*/
/*
 DETAILS D'UNE CATEGORIE
 PATTERN: /categories/{categorie}/{slug}.html [GET]
 CTRL: Categories
 ACTION: show
*/
Route::get('/categories/{categorie}/{slug}.html', 'CategoriesController@show')
      ->where([
              'categorie'   => '[1-9][0-9]*',
              'slug' => '[a-z0-9][a-z0-9\-]*'
            ])
      ->name('categories.show');


/*-----------------------------------
    PAGES
-----------------------------------*/
/*
 DETAILS D'UNE PAGE
 PATERN: /pages/{page}/{slug}.html
 CTRL: PagesController
 ACTION: show
*/
Route::get('/pages/{page}/{slug}.html', 'PagesController@show')
     ->where([
               'page'   => '[1-9][0-9]*',
               'slug'   => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('pages.show');



/*-------------------------------------------------
  MISE A DISPOSITION DE DONNEES POUR CERTAINES VUES
-------------------------------------------------*/

View::composer('pages.menu', function($view){
  $view->with('pages', App\Models\Page::all());
});

View::composer('posts.latest', function($view){
  $view->with('posts', App\Models\Post::orderBy('created_at', 'desc')->take(4)->get());
});

View::composer('categories.liste', function($view){
  $view->with('categories', App\Models\Categorie::orderBy('nom', 'asc')->get());
});

View::composer('projets.slider', function($view){
  $view->with('projets', App\Models\Projet::where('slider', '=', 1)->get());
});

/*
  ROUTE PAR DEFAUT
  PATERN: /
  CTRL: PagesController
  ACTION: show
 */
Route::get('/', 'PagesController@show')->name('accueil');

app/Http/Controllers/CategoriesController.php
<?php
// ./app/Http/Controllers/CategoriesController.php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\DB;
use App\Models\Categorie;

class CategoriesController extends Controller {
  /**
   * Détails d'une catégorie
   * @param  integer $categorie [categorie de la page à afficher]
   * @return [categorie]      [vue categories/show.blade.php]
   */
  public function show(Categorie $categorie) {
    return View::make('categories.show', compact('categorie'));
  }
}

resources/views/categories/liste.blade.php
{{--
  ./resources/views/categories/liste.blade.php
  Description: Liste des catégories
  Données disponibles :
      - $categories : ARRAY(id, nom, created_at, updated_at)
 --}}

 @foreach ($categories as $categorie)
   <li>
     <a href="{{ URL::route('categories.show', ['categorie' => $categorie->id, 'slug' => Str::slug($categorie->nom, '-')]) }}">
       {{ $categorie->nom }}
     </a>
   </li>
 @endforeach

resources/views/categories/show.blade.php
{{--
  ./resources/views/categories/show.blade.php
  Description: Liste des posts pour une catégorie choisie
  variables disponibles :
      - $categorie Categorie
 --}}
@extends('template.defaut')

@section('titre')
  Projets du {{ $categorie->nom }}
@endsection

@section('contenu')
  <div class="section section-breadcrumbs">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Liste de posts pour {{ $categorie->nom }}</h1>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="container">
      <div class="row">
        <!-- Blog Post -->
        @foreach($categorie->posts as $post)
          <div class="col-sm-6">
            <div class="blog-post blog-single-post">
              <div class="single-post-title">
                <h2>{{ $post->titre }}</h2>
              </div>

              <div class="single-post-image">
                <img src="{{ asset('img/blog/'.$post->image) }}" alt="Post Title">
              </div>

              <div class="single-post-info">
                <i class="glyphicon glyphicon-time"></i>{{ \Carbon\Carbon::parse($post->created_at)->format('d M, Y') }}
              </div>

              <div class="single-post-content">
                <p>
                  {{ Str::words($post->texte, 50, '... ') }}
                </p>
                <a href="{{ URL::route('posts.show', ['post' => $post->id, 'slug' => Str::slug($post->titre, '-')]) }}" class="btn">Read more</a>
              </div>
            </div>
          </div>
        @endforeach
        <!-- End Blog Post -->
      </div>
    </div>
  </div>
@endsection